setwd("/Users/guillemangueraalvarado/Desktop/UST/1r semestre/Bioestadística/dades")
examen<-read.table("examen.txt",header=TRUE,sep="",dec=".")
head(examen)
sistema<-factor(examen$sistema,levels = c(0,1),labels = c("sistema A","sistema B"))
zona<-factor(examen$zona,levels = c(0,1),labels = c("alta","baixa"))
median(examen$pluja)            
mean(examen$temp.aigua)             
cor(examen$pluja,examen$residu)
table(sistema)
100*prop.table(table(sistema))
table(sistema,zona)
tapply(examen$residu,sistema,mean)
shapiro.test(examen$residu)
var.test(examen$residu,sistema)
t.test(examen$residu~zona,var.equal=F)
d<-examen$residu-examen$residu_abans
t.test(d,mu=0)
shapiro.test(examen$temp.aigua)
wilcox.test(examen$temp.aigua~sistema)
